version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "MySql2020!"
      MYSQL_DATABASE: "kafkadb"
    ports:
      - "3306:3306"
    volumes:
      - mysql_db_data_container:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network
      
volumes:
  mysql_db_data_container:

networks: 
  mysql-compose-network:
    driver: bridge